"""update settlement

Revision ID: cd566be83dee
Revises: 
Create Date: 2023-12-01 10:59:23.415856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd566be83dee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('profession', sa.String(length=128), nullable=True))
    op.add_column('employee', sa.Column('reason', sa.String(length=128), nullable=True))
    op.alter_column('settlement', 'payer_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settlement', 'payer_name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('employee', 'reason')
    op.drop_column('employee', 'profession')
    # ### end Alembic commands ###
